# Generated by Django 3.1.4 on 2020-12-14 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201213_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features_name', models.CharField(max_length=100, verbose_name='Feature Title')),
                ('feature_icon_html', models.CharField(max_length=100, verbose_name='Feature icon HTML tag')),
            ],
        ),
        migrations.CreateModel(
            name='PageControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Heading Text')),
                ('description_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description Text')),
                ('button_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Button Text')),
            ],
        ),
        migrations.CreateModel(
            name='SectionLayoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100, verbose_name='Section Title')),
                ('has_heading', models.BooleanField(default=False, verbose_name='Section has Heading?')),
                ('has_banner_img', models.BooleanField(default=False, verbose_name='Section has banner Image?')),
                ('has_description', models.BooleanField(default=False, verbose_name='Section has description?')),
                ('has_button', models.BooleanField(default=False, verbose_name='Section has button?')),
                ('has_stats', models.BooleanField(default=False, verbose_name='Section has stats?')),
                ('has_card', models.BooleanField(default=False, verbose_name='Section has card?')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_header_text', models.CharField(max_length=50, verbose_name='Stats Header Text')),
                ('stat_des_text', models.CharField(max_length=255, verbose_name='Stats Description Text')),
            ],
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_page',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='button_page',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='button_page',
            new_name='button_target_page',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='card_header_icon_tag',
            new_name='card_icon_html',
        ),
        migrations.AlterField(
            model_name='page',
            name='page_permalink',
            field=models.CharField(max_length=100, verbose_name='Page PermaLink'),
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='Stat_list',
            field=models.ManyToManyField(max_length=100, to='main.Stat'),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='button_target_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Button', to='main.page'),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='card_list',
            field=models.ManyToManyField(max_length=100, to='main.Card'),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='feature_list',
            field=models.ManyToManyField(max_length=100, to='main.FeatureInfo'),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='section_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sectionlayouttype'),
        ),
        migrations.AddField(
            model_name='pagecontrol',
            name='source_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Source', to='main.page'),
        ),
    ]
