# Generated by Django 3.1.4 on 2020-12-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_card_card_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionlayouttype',
            name='has_feature_list',
            field=models.BooleanField(default=False, verbose_name='Section has Features List?'),
        ),
    ]
