# Generated by Django 3.1.4 on 2020-12-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sectionlayouttype_has_feature_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontrol',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='sections'),
        ),
    ]
