# Generated by Django 3.1.4 on 2020-12-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201214_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontrol',
            name='refernce_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference Name'),
        ),
    ]
