# Generated by Django 3.1.4 on 2020-12-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_pagecontrol_refernce_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontrol',
            name='Stat_list',
            field=models.ManyToManyField(blank=True, max_length=100, to='main.Stat'),
        ),
        migrations.AlterField(
            model_name='pagecontrol',
            name='card_list',
            field=models.ManyToManyField(blank=True, max_length=100, to='main.Card'),
        ),
        migrations.AlterField(
            model_name='pagecontrol',
            name='feature_list',
            field=models.ManyToManyField(blank=True, max_length=100, to='main.FeatureInfo'),
        ),
    ]
