# Generated by Django 3.1.4 on 2020-12-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201214_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontrol',
            name='description_text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description Text'),
        ),
    ]
